export default[
  {text: '总公司', value: '100',
    children: [
      {text: '总公司', value: '100'},
      { text: '领导', value:'101' },
      { text: '办公室(党办、董办)', value:'102' },
      { text: '人力资源部(党委组织部)', value:'103' },
      { text: '党群工作部', value:'104' },
      { text: '计划财务部', value:'105' },
      { text: '规划发展部', value:'106' },
      { text: '精算部', value:'107' },
      { text: '营销管理部', value:'108' },
      { text: '资产管理部', value:'109' },
      { text: '车险部', value:'110' },
      { text: '非车险部(再保险部)', value:'111' },
      { text: '健康保险事业部', value:'142' },
      { text: '信用保证保险一部', value:'112' },
      { text: '信用保证保险二部', value:'113' },
      { text: '农业保险部', value:'114' },
      { text: '客户服务部', value:'115' },
      { text: '信息技术部', value:'116' },
      { text: '电子商务部', value:'117' },
      { text: '法律合规部', value:'118' },
      { text: '审计部', value:'119' },
      { text: '纪委', value:'120' },
      { text: '重点客户部一部', value:'1211' },
      { text: '重点客户部二部', value:'1212' },
      { text: '重点客户部三部', value:'1213' },
      { text: '泰盛保险销售公司', value:'122' },
      { text: '民间资本公司', value:'123' },
      { text: '*电话中心', value:'124' },
      { text: 'IT外包', value:'1401' },
      { text: '办公室外包', value:'1402' },
    ]
  },
  {text: '山东分公司', value: '125',
    children: [
      {text: '山东分公司', value: '125'},
      { text: '济宁中支', value:'1251' },
      { text: '临沂中支', value:'1252' },
      { text: '潍坊中支', value:'1253' },
      { text: '淄博中支', value:'1254' },
      { text: '聊城中支', value:'1255' },
      { text: '东营中支', value:'1256' },
      { text: '烟台中支', value:'1257' },
      { text: '威海中支', value:'1258' },
      { text: '济南中支', value:'1259' },
      { text: '泰安中支', value:'1260' },
      { text: '枣庄中支', value:'1261' },
      { text: '滨州中支', value:'1262' },
      { text: '菏泽中支', value:'1263' },
      { text: '德州中支', value:'1264' },
      { text: '日照中支', value:'1265' },
      { text: '莱芜中支', value:'1266' },
      { text: '市场部', value:'1408' },
    ]
  },
  {text: '青岛分公司', value: '127',
    children: [
      {text: '青岛分公司', value: '127'},
      { text: '胶州支公司', value:'1271' },
      { text: '城阳支公司', value:'1272' },
      { text: '黄岛支公司', value:'1273' },
      { text: '平度支公司', value:'1274' },
      { text: '即墨支公司', value:'1275' }
    ]
  },
  {text: '江苏分公司', value: '128',
    children: [
      {text: '江苏分公司', value: '128'},
      { text: '镇江中支', value:'1281' },
      { text: '泰州中支', value:'1282' },
      { text: '南通中支', value:'1283' },
      { text: '常州中支', value:'1284' },
      { text: '无锡中支', value:'1285' },
      { text: '盐城中支', value:'1286' },
      { text: '徐州中支', value:'1287' },
      { text: '连云港中支', value:'1288' }
    ]
  },
  {text: '河北分公司', value: '129',
    children: [
      {text: '河北分公司', value: '129'},
      { text: '邯郸中支', value:'1291' },
      { text: '邢台中支', value:'1292' },
      { text: '保定中支', value:'1293' },
      { text: '沧州中支', value:'1294' },
      { text: '石家庄中支', value:'1295' },
      { text: '张家口中支', value:'1296' },
      { text: '唐山中支', value:'1297' },
      { text: '承德中支', value:'1298' }
    ]
  },
  {text: '内蒙古分公司', value: '130',
    children: [
      {text: '内蒙古分公司', value: '130'},
      { text: '鄂尔多斯中支', value:'1301' },
      { text: '包头中支', value:'1302' },
      { text: '赤峰中支', value:'1303' },
      { text: '兴安盟中支', value:'1304' },
      { text: '巴彦淖尔中支', value:'1305' },
      { text: '呼伦贝尔中支', value:'1306' }
    ]
  },
  {text: '浙江分公司', value: '131',
    children: [
      {text: '浙江分公司', value: '131'},
      { text: '萧山支公司', value:'1311' },
      { text: '杭州营业部', value:'1312' },
      { text: '台州中支', value:'1313' },
      { text: '湖州中支', value:'1314' },
      { text: '金华中支', value:'1315' },
      { text: '嘉兴中支', value:'1316' }
    ]
  },
  {text: '宁波分公司', value: '132',
    children: [
      {text: '宁波分公司', value: '132'},
      { text: '鄞州支公司', value:'1321' },
      { text: '北仑支公司', value:'1322' },
      { text: '余姚支公司', value:'1323' }
    ]
  },
  {text: '北京分公司', value: '133',
    children: [{text: '北京分公司', value: '133'}]
  },
  {text: '河南分公司', value: '134',
    children: [
      {text: '河南分公司', value: '134'},
      { text: '洛阳中支', value:'1341' },
      { text: '安阳中支', value:'1342' },
      { text: '虞城营销服务部', value:'1343' },
      { text: '新乡中支', value:'1344' },
      { text: '兰考营销服务部', value:'1345' },
      { text: '商水营销服务部', value:'1346' },
      { text: '鹤壁营销服务部', value:'1347' },
      { text: '金水营销服务部', value:'1348' },
      { text: '濮阳营销服务部', value:'1349' },
      { text: '南阳中支', value:'1350' },
      { text: '周口中支', value:'1351' },
      { text: '郑州中支(筹)', value:'1352' },
      { text: '计划财务部', value:'1353' },
      { text: '公司业务一部', value:'1354' },
      { text: '非车一部', value:'1355' },
      { text: '个代一部', value:'1356' },
      { text: '经代业务一部', value:'1357' },
    ]
  },
  {text: '陕西分公司', value: '136',
    children: [{text: '陕西分公司', value: '136'}]
  },
  {text: '山西分公司', value: '137',
    children: [
      {text: '山西分公司', value: '137'},
      { text: '运城中支', value:'1371' },
      { text: '晋中中支(筹)', value:'1372' },
      { text: '非车险业务部', value:'1373' },
      { text: '公司业务一部', value:'1374' },
      { text: '公司业务二部', value:'1375' },
      { text: '潞州支公司', value:'1376' },
      { text: '业务一部', value:'1377' },
      { text: '业务三部', value:'1378' },
      { text: '直销业务部二部', value:'1379' },
      { text: '直销业务部三部', value:'1380' },
      { text: '直销业务部四部', value:'1381' },
      { text: '直销业务部五部', value:'1382' },
      { text: '直销业务部七部', value:'1383' },
      { text: '直销业务部八部', value:'1384' },
      { text: '直销业务部九部', value:'1385' },
      { text: '直销业务部十二部', value:'1386' },
      { text: '直销业务部十三部', value:'1387' },
    ]
  },
  {text: '四川分公司', value: '138',
    children: [{text: '四川分公司', value: '138'}]
  },
  {text: '天津分公司', value: '139',
    children: [{text: '天津分公司', value: '139'}]
  }
]
