package com.tsvhlpom.batchdata.vhlplatdatacheck.domain;

import lombok.Data;

import java.util.Date;

/**
 * TrdPlyPacketVO generated by MyEclipse Persistence Tools
 */

@Data
public class TrdAppSendPacketDO {

	private String pkId;
	private String CQryCde;
	private String CConfirmCde;
	private String CPlateNo;
	private String CEngNo;
	private Date TSendTm;
	private String CSendPacket;
	private String CAppNo;
	private String CTradeTyp;
	private String CResvTxt1;
	private String CResvTxt2;
	private String CResvTxt3;
	private String CResvTxt4;
	private String CResvTxt5;
	private String CTransMrk;
	private Date TTransTm;
}
